repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
-   repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake -r -i --remove-all-unused-imports --remove-unused-variables
        language: system
        types: [ python ]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy .
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        types: [python]
      - id: kacl-verify
        name: kacl-verify
        entry: kacl-cli verify
        language: system
        files: 'CHANGELOG.md'
        pass_filenames: false
